name: un_dia_mas
description: Una app Flutter para apoyo en la recuperaciÃ³n de adicciones.
publish_to: "none"

# Build number +1 porque hemos cambiado dependencias
version: 1.0.0+9          

environment:
  sdk: ">=2.19.0 <4.0.0"     # â¬…ï¸ compatible con DartÂ 2.19â€‘3.x

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:      # incluye intlÂ 0.20.2
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^5.0.0
  just_audio: ^0.9.36
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  fl_chart: ^0.66.0
  flutter_markdown: ^0.6.18
  flutter_secure_storage: ^9.0.0
  # ðŸ‘‡  intl YA NO se declara aquÃ­; viene transitiva de flutter_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/quotes.json
    - assets/audio/relax60s.mp3
    - assets/data/reflections.json
    - packages/timezone/data/latest_all.tzf
